In [9]:
import pandas as pd

In [10]:
results = pd.read_csv("../../results/results_log.csv")

results

                 model  accuracy  precision    recall        f1   auc_roc
0  Logistic Regression  0.714286   0.608696  0.518519  0.560000  0.822963
1                   DT  0.694805   0.666667  0.259259  0.373333  0.788056
2                   RF  0.746753   0.653061  0.592593  0.621359  0.814259
3                  SVM  0.766234   0.686275  0.636364  0.660377  0.737374
4                  MLP  0.746753   0.641509  0.629630  0.635514  0.843889

In [11]:
results["model"] = results["model"].replace({
    "DT":"Decision Tree",
    "RF":"Random Forest",
    "LR":"Logistic Regression",
    "SVM":"Support Vector Machine",
    "MLP":"Multi-Layer Perceptron"
})

results

                    model  accuracy  precision    recall        f1   auc_roc
0     Logistic Regression  0.714286   0.608696  0.518519  0.560000  0.822963
1           Decision Tree  0.694805   0.666667  0.259259  0.373333  0.788056
2           Random Forest  0.746753   0.653061  0.592593  0.621359  0.814259
3  Support Vector Machine  0.766234   0.686275  0.636364  0.660377  0.737374
4  Multi-Layer Perceptron  0.746753   0.641509  0.629630  0.635514  0.843889

In [12]:
results = results.round(4)

results

                    model  accuracy  precision  recall      f1  auc_roc
0     Logistic Regression    0.7143     0.6087  0.5185  0.5600   0.8230
1           Decision Tree    0.6948     0.6667  0.2593  0.3733   0.7881
2           Random Forest    0.7468     0.6531  0.5926  0.6214   0.8143
3  Support Vector Machine    0.7662     0.6863  0.6364  0.6604   0.7374
4  Multi-Layer Perceptron    0.7468     0.6415  0.6296  0.6355   0.8439

In [13]:
results.to_csv(
    "../../results/final_results_table.csv",
    index=False
)

print("Final Results Table saved.")

Final Results Table saved.

In [14]:
print(results)

                    model  accuracy  precision  recall      f1  auc_roc
0     Logistic Regression    0.7143     0.6087  0.5185  0.5600   0.8230
1           Decision Tree    0.6948     0.6667  0.2593  0.3733   0.7881
2           Random Forest    0.7468     0.6531  0.5926  0.6214   0.8143
3  Support Vector Machine    0.7662     0.6863  0.6364  0.6604   0.7374
4  Multi-Layer Perceptron    0.7468     0.6415  0.6296  0.6355   0.8439

In [15]:
import pandas as pd

# Load the proposed framework results generated from the ablation study
proposed_results = pd.read_csv(
    "../../results/week5/ablation_results.csv"
)

proposed_results = proposed_results.round({
    "Accuracy": 4,
    "Precision": 4,
    "Recall": 4,
    "F1 Score": 4
})

proposed_results

          Configuration  Accuracy  Precision  Recall  F1 Score
0            Static MLP    0.7468     0.6415  0.6296    0.6355
1          Adaptive MLP    0.8095     0.8333  0.6250    0.7143
2  Adaptive + Proactive    0.7500     0.5714  0.6957    0.6275

In [16]:
import os

os.makedirs("../../results", exist_ok=True)

proposed_results.to_csv(
    "../../results/proposed_framework_results.csv",
    index=False
)

print("Proposed framework results saved successfully!")

Proposed framework results saved successfully!